#!/bin/sh

set -x
echo "executing assemble script..."

cd /tmp/src
whoami
service postgresql start
GRADLE_OPTS="-Dorg.gradle.daemon=false -Xms400m -Xmx400m" ./gradlew build --debug
mv ./build/libs/*.jar ~
